# Generated by Django 4.1.2 on 2023-12-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Properties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=1000)),
                ("address", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("url", models.URLField(max_length=100)),
                (
                    "building_type",
                    models.CharField(max_length=20, verbose_name="Շինության տիպ"),
                ),
                (
                    "new_building",
                    models.CharField(max_length=5, verbose_name="Նորակառույց"),
                ),
                ("elevator", models.CharField(max_length=10, verbose_name="Վերելակ")),
                ("count_of_floors", models.IntegerField(verbose_name="Հարկերի քանակ")),
                ("area", models.IntegerField(verbose_name="Մակերես")),
                ("rooms", models.IntegerField(verbose_name="Սենյակների քանակ")),
                (
                    "bathrooms",
                    models.IntegerField(verbose_name="Սանհանգույցների քանակ"),
                ),
                ("floor", models.IntegerField(verbose_name="Հարկ")),
                ("balcony", models.CharField(max_length=10, verbose_name="Պատշգամբ")),
                (
                    "ceiling_hight",
                    models.IntegerField(verbose_name="Առաստաղի բարձրություն"),
                ),
                ("furniture", models.CharField(max_length=10, verbose_name="Կահույք")),
                (
                    "renovation",
                    models.CharField(max_length=50, verbose_name="Վորանորոգում"),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Նկարագիր"),
                ),
            ],
        ),
    ]
