# Generated by Django 4.1.2 on 2023-12-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="properties",
            old_name="ceiling_hight",
            new_name="առաստաղ",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="furniture",
            new_name="կահույք",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="floor",
            new_name="հարկ",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="count_of_floors",
            new_name="հարկերի_քանակ",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="area",
            new_name="մակերես",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="description",
            new_name="նկարագիր",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="new_building",
            new_name="նորակառույց",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="building_type",
            new_name="շինության_տիպ",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="balcony",
            new_name="պատշգամբ",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="bathrooms",
            new_name="սանհանգույց",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="rooms",
            new_name="սենյակ",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="renovation",
            new_name="վերանորոգում",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="elevator",
            new_name="վերելակ",
        ),
    ]
