# Generated by Django 4.1.2 on 2023-12-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_rename_ceiling_hight_properties_առաստաղ_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="properties",
            old_name="առաստաղ",
            new_name="Առաստաղի_բարձրություն",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="մակերես",
            new_name="Ընդհանուր_մակերես",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="հարկ",
            new_name="Հարկ",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="պատշգամբ",
            new_name="Պատշգամբ",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="սանհանգույց",
            new_name="Սանհանգույցների_քանակ",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="սենյակ",
            new_name="Սենյակների_քանակ",
        ),
        migrations.RemoveField(
            model_name="properties",
            name="կահույք",
        ),
        migrations.RemoveField(
            model_name="properties",
            name="հարկերի_քանակ",
        ),
        migrations.RemoveField(
            model_name="properties",
            name="նորակառույց",
        ),
        migrations.RemoveField(
            model_name="properties",
            name="շինության_տիպ",
        ),
        migrations.RemoveField(
            model_name="properties",
            name="վերանորոգում",
        ),
        migrations.RemoveField(
            model_name="properties",
            name="վերելակ",
        ),
        migrations.AddField(
            model_name="properties",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="properties",
            name="long",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="properties",
            name="Առկա_են",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="properties",
            name="Թույլատրվում_են_ընտանի_կենդանիներ",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="properties",
            name="Կայանատեղի",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Կայանատեղի"
            ),
        ),
        migrations.AddField(
            model_name="properties",
            name="Կանխավճար",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="properties",
            name="Կարելի_է_երեխաների_հետ",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="properties",
            name="Կենցաղային_տեխնիկա",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="properties",
            name="Կոլունալ_վճարումներ",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Կոմունալ վճարումներ"
            ),
        ),
        migrations.AddField(
            model_name="properties",
            name="Հարմարոըտթյուններ",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="properties",
            name="Տեսարաններ_պատուհաններից",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="properties",
            name="Կահույք",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Կահույք"
            ),
        ),
        migrations.AddField(
            model_name="properties",
            name="Հարկերի_քանակ",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Հարկերի քանակ"
            ),
        ),
        migrations.AddField(
            model_name="properties",
            name="Նորակառույց",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Նորակառույց"
            ),
        ),
        migrations.AddField(
            model_name="properties",
            name="Շինության_տիպ",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Շինության տիպ"
            ),
        ),
        migrations.AddField(
            model_name="properties",
            name="Վերանորոգում",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Վորանորոգում"
            ),
        ),
        migrations.AddField(
            model_name="properties",
            name="Վերելակ",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Վերելակ"
            ),
        ),
    ]
