# Generated by Django 4.1.2 on 2023-12-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_rename_առաստաղ_properties_առաստաղի_բարձրություն_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Properties",
            new_name="Property_rent",
        ),
    ]
