# Generated by Django 4.1.2 on 2023-12-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0004_rename_properties_property_rent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property_rent",
            name="lat",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="property_rent",
            name="long",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="property_rent",
            name="price",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="property_rent",
            name="Առաստաղի_բարձրություն",
            field=models.CharField(max_length=10, verbose_name="Առաստաղի բարձրություն"),
        ),
        migrations.AlterField(
            model_name="property_rent",
            name="Հարկ",
            field=models.CharField(max_length=10, verbose_name="Հարկ"),
        ),
        migrations.AlterField(
            model_name="property_rent",
            name="Հարկերի_քանակ",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Հարկերի քանակ"
            ),
        ),
        migrations.AlterField(
            model_name="property_rent",
            name="Սանհանգույցների_քանակ",
            field=models.CharField(max_length=10, verbose_name="Սանհանգույցների քանակ"),
        ),
        migrations.AlterField(
            model_name="property_rent",
            name="Սենյակների_քանակ",
            field=models.CharField(max_length=10, verbose_name="Սենյակների քանակ"),
        ),
    ]
