# Generated by Django 4.1.2 on 2023-12-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0005_alter_property_rent_lat_alter_property_rent_long_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property_rent",
            name="Ընդհանուր_մակերես",
            field=models.CharField(max_length=10, verbose_name="Մակերես"),
        ),
    ]
