# Generated by Django 4.1.2 on 2023-12-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0006_alter_property_rent_ընդհանուր_մակերես"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property_rent",
            old_name="Հարմարոըտթյուններ",
            new_name="Հարմարություններ",
        ),
        migrations.RenameField(
            model_name="property_rent",
            old_name="նկարագիր",
            new_name="Նկարագիր",
        ),
    ]
