# Generated by Django 4.1.2 on 2023-12-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "houses",
            "0007_rename_հարմարոըտթյուններ_property_rent_հարմարություններ_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="property_rent",
            old_name="Կոլունալ_վճարումներ",
            new_name="Կոմունալ_վճարումներ",
        ),
    ]
