# Generated by Django 4.1.2 on 2023-12-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0008_rename_կոլունալ_վճարումներ_property_rent_կոմունալ_վճարումներ"),
    ]

    operations = [
        migrations.AddField(
            model_name="property_rent",
            name="image",
            field=models.ImageField(
                blank=True, height_field=287, null=True, upload_to="", width_field=480
            ),
        ),
    ]
