# Generated by Django 4.1.2 on 2023-12-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0009_property_rent_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property_sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Պատշգամբ", models.CharField(max_length=20, verbose_name="Պատշգամբ")),
                (
                    "Կայանատեղի",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Կայանատեղի"
                    ),
                ),
                (
                    "Ընդհանուր_մակերես",
                    models.CharField(max_length=10, verbose_name="Մակերես"),
                ),
                ("lat", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "Շինության_տիպ",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Շինության տիպ",
                    ),
                ),
                (
                    "Վերանորոգում",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Վորանորոգում",
                    ),
                ),
                ("url", models.URLField(max_length=100)),
                (
                    "Կահույք",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Կահույք"
                    ),
                ),
                ("price", models.CharField(max_length=10)),
                (
                    "Կենցաղային_տեխնիկա",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("Նկարագիր", models.CharField(max_length=500, verbose_name="Նկարագիր")),
                (
                    "Առաստաղի_բարձրություն",
                    models.CharField(
                        max_length=10, verbose_name="Առաստաղի բարձրություն"
                    ),
                ),
                ("Հարկ", models.CharField(max_length=10, verbose_name="Հարկ")),
                ("address", models.CharField(max_length=200)),
                (
                    "Տեսարաններ_պատուհաններից",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Նորակառույց",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Նորակառույց"
                    ),
                ),
                (
                    "Սենյակների_քանակ",
                    models.CharField(max_length=10, verbose_name="Սենյակների քանակ"),
                ),
                ("Առկա_են", models.CharField(blank=True, max_length=100, null=True)),
                ("title", models.TextField(max_length=1000)),
                ("long", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "Հարկերի_քանակ",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Հարկերի քանակ",
                    ),
                ),
                (
                    "Սանհանգույցների_քանակ",
                    models.CharField(
                        max_length=50, verbose_name="Սանհանգույցների քանակ"
                    ),
                ),
                (
                    "Վերելակ",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Վերելակ"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="rent_properties/",
                        verbose_name="Image",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="property_rent",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="rent_properties/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="property_rent",
            name="Կանխավճար",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="property_rent",
            name="Կենցաղային_տեխնիկա",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="property_rent",
            name="Պատշգամբ",
            field=models.CharField(max_length=20, verbose_name="Պատշգամբ"),
        ),
        migrations.AlterField(
            model_name="property_rent",
            name="Սանհանգույցների_քանակ",
            field=models.CharField(max_length=50, verbose_name="Սանհանգույցների քանակ"),
        ),
        migrations.AlterField(
            model_name="property_rent",
            name="Վերելակ",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Վերելակ"
            ),
        ),
    ]
